service: trpc-hexagonal-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  app:
    handler: src/app/handler/ReservationHandler.handler
    environment:
      DB_HOST: your-db-host
      DB_USER: your-db-user
      DB_PASSWORD: your-db-password
      DB_NAME: resort_booking
    events:
      - http:
          path: trpc
          method: post

plugins:
  - serverless-plugin-typescript
