service: trpc-reservation-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 4000

package:
  individually: true